development:
  type: smtp
  server: 'ssssssmtp.sendgrid.net'
  username: 'notifications@sitterscout.com'
  password: 'ChiefScout'
  port: 25
  ssl: true
  
test:
  type: pop
  server: localhost
  username: username
  password: password
  
production:
    type: smtp
    server: 'ssssssmtp.sendgrid.net'
    username: 'notifications@sitterscout.com'
    password: 'ChiefScout'
    port: 25
    authentication: true

